theme: jekyll-theme-midnight
title: He(y|j) there!
description:  Just Another General AI toolbox <br> <a href="https://kostis-s-z.github.io/Jag.AI">Project Jag.AI</a>  | <a href="https://kostis-s-z.github.io/Jag.AI/blog">Blog</a>  | <a href="https://kostis-s-z.github.io/">Personal Page</a> 
email: kosz@kth.se
baseurl: ""
url: https://kostis-s-z.github.io/
github_username: Kostis-S-Z
